/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package monoopoly;
/**
 * autogenerated class from Gradle init task.
 */
public class Library {

    /**
     *  autogenerated method.
     *  @return true.
     */
    public final boolean someLibraryMethod() {
        return true;
    }
}
